# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodoApp
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'

  pod 'RNCViewpager', :path => '../node_modules/@react-native-community/viewpager'

  target 'TodoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TodoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TodoApp-tvOS

  target 'TodoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
