import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
 "en-US":{
   welcome:"Welcome TodoApp",
   settings:"Settings",
   whatIsHoursTitle:"What is Work hours?",
   whatIsHoursContent:"Each day in the week will have certain hours in the day will be allotted to work. Also capture Awake hours",
   language: "Language",
   languageInfo: "This application is available in several languages.",
   skip: "Skip",
   workHours: "Work Hours",
   workHoursInfo: "",
   disturbanceLevel: "Disturbance Level",
   disturbanceLevelInfo: "",
   timeBlocks: "Time Blocks",
   timeBlocksInfo: "",
 },
 en:{
   welcome:"Welcome Todo-App",
   settings:"Settings",
   whatIsHoursTitle:"What is Work hours?",
   whatIsHoursContent:"Each day in the week will have certain hours in the day will be allotted to work. Also capture Awake hours",
   language: "Language",
   languageInfo: "This application is available in several languages.",
   skip: "Skip",
   workHours: "Work Hours",
   workHoursInfo: "",
   disturbanceLevel: "Disturbance Level",
   disturbanceLevelInfo: "",
   timeBlocks: "Time Blocks",
   timeBlocksInfo: "",
 },
 de: {
   welcome:"herzlich willkommen",
   settings:"die Einstellungen",
   whatIsHoursTitle:"Was ist Arbeitszeit?",
   whatIsHoursContent:"Jedem Tag in der Woche werden bestimmte Stunden am Tag zur Arbeit zugewiesen. Erfassen Sie auch die Wachstunden",
   language: "Language",
   languageInfo: "Diese Anwendung ist in mehreren Sprachen verfügbar.",
   skip: "überspringen",
   workHours: "Arbeitsstunden",
   workHoursInfo: "",
   disturbanceLevel: "Störpegel",
   disturbanceLevelInfo: "",
   timeBlocks: "Zeitblöcke",
   timeBlocksInfo: "",
 }
});
